import { AuthProvider } from "@/utility/AuthProvider";
import ReactQueryProvider from "@/utility/QueryProvider";
import { Inter } from "next/font/google";
import { CookiesProvider } from "next-client-cookies/server";
import "./globals.css";
import React from "react";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Radiant Glow Dental Clinic",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${inter.variable} antialiased prose underline-offset-8`}
      >
        <CookiesProvider>
          <AuthProvider>
            <ReactQueryProvider>
              <main>
                {children}
              </main>
              <Toaster />
            </ReactQueryProvider>
          </AuthProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
